### PR TITLE
added sentry, some more docs and i18n

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pydanny** [comment]
Hey Evgeny,

All of this is awesome but its too much for a single pull request. There are docs, sentry, and i18n all mixed together and that goes against our small pull request rules (which is why we like feature branches). Making sure that this all works is going to be unbelievably challenging.

However, I'll see if I can figure out how to cherrypick individual files so we don't lose your effort.

**Comment by pydanny** [comment]
Hey Evgeny,

I'm going to try and cherrypick out the best parts hopefully later today. This is great work and I don't want to lose any of it. :)

Danny

**Comment by ptone** [comment]
If you want I can bring a can of rebase whoop-ass to it and resubmit the work, I think Evgeny's author tag remains intact

**Comment by ptone** [comment]
cherrypicking should work pretty well in this case, often/usually you would have >1 commit for each feature(should-a-been-a-branch), but in this case they look close to 1:1, so cherry-picking, rebasing are about the same

PS I also find github's UI way to easy to close issues/pulls on comment submit

**Pull request closed without merging**
