### PR TITLE
Git regex improvement

### PR DESCRIPTION
**Pull request by ptone**
allows for alternative valid protocol portions of url

### CODE REVIEW

**Comment by pydanny** [comment]
Failing full test suite. Please patch and resubmit!

**Comment by ptone** [comment]
as of right now, this does not pass full tests, but that is because this actually fixes something that reveals something else as broken

some slurper tests are now failing because package repo_url in a test is coming back as:

```
http://github.com/pydanny/django-uni-form/tree/master
```

the http instead of https was resulting in this not being recognized as a github repo

this pull fixes that, but now fetch_metadata bombs because the tree/master part is invalid for the github api

so in this case, slurper tests SHOULD fail.  So I think this is ready for merge - I'll see if I can fix the slurper stuff

**Comment by pydanny** [comment]
Um... are you saying this is ready to go? Or no?

**Comment by ptone** [comment]
YES - but just a warning tests will break into you also pull my slurper fixes (documented why over on that pull)

**Comment by pydanny** [comment]
This isn't working and had to reverse it. Test suite runs fine but if you actually add github or bitbucket accounts into the fields it doesn't have the right data in the form fields.

Try: https://github.com/cartwheelweb/packaginator.

Please fix and resubmit.

**Comment by ptone** [comment]
Danny - does your closing this again mean you either fixed it yourself or found the problem to be somewhere else?

-P

**Comment by ptone** [comment]
yes - when I wrote this, had no idea the regex was being slurped directly into javascript and used to capture there! Doh.  This regex change should fix that.

**Comment by pydanny** [comment]
Accepted. Had to modify how test_repo handled launchpad uploads.

**Pull request merged**
