### PR TITLE
All style

### PR DESCRIPTION
**Pull request by skotcarruth**
///// completed ////

• changed name of djangopackages.css to bass.css
• removed unused .css files
• removed searchv1/base.html (now unused)
• renamed templates/grid/snippets/grid2.html to grid.html, replace references, and remove unused file
• renamed templates/package/includes/package3.html to package.html, replace references, and remove unused file
• added the download icon PSD file
• beautified the header search box

### CODE REVIEW

**Comment by ptone** [comment]
Note that this might have some easily resolved conflicts with the pypi factor out, but will have some changes /improvements that will need to be ported over to the pypackage. This kind of thing is where a few more blocks might be nice.

**Comment by pydanny** [comment]
Preston, we don't want blocks attached to this pull request and this was discussed during the sprint. Design is a separate issue from architecture.

**Comment by ptone** [comment]
just making some advance notes of some possible merge conflicts as a heads up

**Comment by pydanny** [comment]
Merge conflicts aren't that hard. My merge-fu is very strong. :)

**Pull request merged**
