### PR TITLE
Add /versions/[package]

### PR DESCRIPTION
**Pull request by mrj0**
This is for issue 15.

### CODE REVIEW

**Comment by pydanny** [comment]
Some issues I'll look at:

```
Going to the URI for a version returns an error message
No tests yet
Nothing in the docs
```

**Comment by pydanny** [comment]
Can you or ray commit the working stuff?

**Comment by mrj0** [comment]
Ray had some changes for a different issue, not sure what state they are in.

On Mon, Apr 11, 2011 at 11:56 AM, pydanny
reply@reply.github.com
wrote:

**Comment by rayleyva** [comment]
@mrj0 Did you commit the s/version/versions/ change?

**Comment by mrj0** [comment]
I didn't, no. I still don't get what's going on with this thing. I have 'versions' in there now, that was in the original pull request, and it works...

I'm experimenting with django-rest-framework, instead. Maybe just kill off this pull request and focus on the api v2.

**Comment by pydanny** [comment]
Hey,

I like the idea of doing an API V2 to address this issue. Consider this ticket and headache closed. :P

I'm not sure what benefit we get out of django-rest-framework. We've got too many custom requirements for heirarchical datasets to make it worth the effort of getting that to work. I think a better route would be https://github.com/sorl/django-cbv or Django 1.3 class based views since that is class based views of tastypie, piston, and django-rest-framework.

In any case, thanks for all the hard, hard work!

**Comment by mrj0** [comment]
Ah, okay. Well, I went ahead and pushed what I had been playing with:

https://github.com/mrj0/packaginator/commit/450bb2ed200dcf97cc601fd607dc2ea0bbf66b4f

Using the framework gets you some nice Accept header content format
negotiation stuff for free. And, as you can see, it looks a whole lot
like the CBVs.

But that project is pretty early stage, even though it seems to work
well so far.

**Pull request closed without merging**
