### PR TITLE
Sample project refactor

### PR DESCRIPTION
**Pull request by ptone**
this involves changing how we protect templates and settings in a deployment

### CODE REVIEW

**Comment by audreyfeldroy** [comment]
I've looked everything over.  Looks like a lot of good cleanup work.  

The one thing I am nervous about is the base_templates change.  I see how it can be a good way of keeping the templates clean enough to allow people to change them for their sites and still fetch upstream Packaginator changes.  But it's also a non-standard way of doing things which can cause confusion, in the same way that running custom magic setup scripts can cause confusion.  

And it's something we'd probably have to change back if we were to let people "pip install Packaginator" in the future.

I am not accepting this yet because I need some time to think about it.  If you can point me to some examples of popular Django frameworks that people have created that do the same thing with their templates, that would help convince me that this is a good idea.

**Comment by ptone** [comment]
this is a pretty major FS layout change, so it should be done conservatively.  I do think that it can/should be done at the same time as any reorg involved in making packaginator a package itself, so that disruption is minimized.

I don't think there is a standard way of doing templates in a reusable project, maybe I'll ask el convore for some input

**Comment by pydanny** [comment]
I've been thinking that we should stay with the /templates convention. We'll advise people to do customization in a custom.css file and change the logo.

If someone wants to change the templates directory, we'll let them but say it will hurt their ability to handle patches.

if someone is smart enough to add another template directory, then more power to them. But I don't want to explain it to them because then we'll have to explain template overloading and all that jazz.

**Comment by ptone** [comment]
I also was thinking about this last night in the context of how I might get started on a packaginator instance without this in master, and realized that the inverse of this approach is just as easy and clearer.  That is, create a site_templates folder and add that to template_dirs for overrides.

closing this issue out

**Pull request closed without merging**
