### PR TITLE
move all celery related stuff into packaginator-celery

### PR DESCRIPTION
**Pull request by ptone**
IMHO core packaginator should be a rather lean, easy to run project, and add ons should be combinations of code and docs to make it more full featured

I've also been thinking about how to redo the tasks stuff as I've moved the old slurper functionality into the core pypackage model

other candidates for this type of factoring are:

haystack-search
repo backends

hooks and signals can be built into core packaginator as needed to support this added functionality

I'm inclined to get this done before working a bunch of celery stuff into the pypackage/pypi stuff. Since so little has been done - shouldn't be too hard. Been reading some celery docs, so gradually getting up to speed with celery more than skin deep

### CODE REVIEW

**Comment by pydanny** [comment]
Alas, this needs a lot of work. Requirements and local_settings.py.example and the docs all need to be addressed.

**Comment by ptone** [comment]
These were missed due to some over eager default filtering of filetypes in ack which I'm still getting used to.  There are still a couple references in the pypi app, but this goes away with the pypi-factorout

I've also stashed all the relevant bits in a packaginator-celery package if you want to create a repo for that I can push it up, but its mostly just saved bits in a scratchpad folder for now.

**Comment by ptone** [comment]
BTW - you don't actually say whether or not you are in favor of this approach

**Comment by tmitchell** [comment]
I don't currently have the broad view of who the intended end users are of Packaginator, so I can't say how easy to run it needs to be.  Haystack support out of the box is relatively painless with the 'simple' backend, but I'm in favor of modularization if it makes sense.  Take a look at cartwheelweb/packaginator#183 and let me know if we need to take this to 11.  Currently Haystack can be disabled with the setting `PACKAGINATOR_SEARCH_HAYSTACK = False` so it should be easy enough to extract entirely.

**Comment by pydanny** [comment]
How did a comment on Haystack get into the celery discussion? :)

As for factoring out stuff, working on the architecture now.

**Comment by tmitchell** [comment]
I was just perusing the outstanding pull requests and he specifically called out haystack for similar treatment.  I figured it wasn't worth forking another issue until someone more opinionated on the matter weighed in.  The better question is, what are you doing responding to random off-topic comments? You're supposed to be heads-down and not thinking about anything else!

**Comment by pydanny** [comment]
Upon a lot of reflection, Packaginator is no longer a project for beginners or people just getting started. And celery is rapidly  becoming an important issue. Abstracting this into it's own project is no longer a valid approach.

**Pull request closed without merging**
