### PR TITLE
Smart grid (always on)

### PR DESCRIPTION
**Pull request by jimallman**
Here's (finally!) the first set of changes to add the jQuery dataTable plugin's features to the package-comparison grid. In this version, the "smart grid" should appear in any browser that supports Javascript. Non-JS browsers will show a simple, oversized grid as before.

I was planning to do smaller "baby steps", as Audrey requested, but none of the smaller changes were testable, since they didn't  _do_ anything or look any different. I've successfully tested this branch in IE8, IE7 (via IE8's compatibility mode), Firefox/Win, Firefox/Mac, Chrome/Mac, and Safari.

Next up, I'm planning to restore the toggle between smart and simple grids. I don't know the best practice in situations like this (serial pull requests), so I'm planning to merge this branch into my local master, keep it around to make any requested changes, and create a new branch (from master) for the next steps. Hope that's OK.

### CODE REVIEW

**Comment by jimallman** [comment]
I have some other notes and background information in the related ticket #156:
https://github.com/cartwheelweb/packaginator/issues/156

**Comment by jimallman** [comment]
Sorry, I clicked the big shiny "Comment & Close" button by mistake.  :-/

**Comment by pydanny** [comment]
Hey Jim,

Sorry for the REALLY long delay on this and other pull requests you've given. Over the next few days I get to focus 100% of my time on this project. My plan is to get your work in ASAP. Thank you so much for your patience!

Danny

**Comment by jimallman** [comment]
Awesome! Thanks for letting me know.  =jimA=

**Pull request merged**
