### PR TITLE
[deferred] South conversion

### PR DESCRIPTION
**Pull request by ptone**
I think others have to run with --fake, not sure, I didn't snapshot my DB, so I can't try to apply these migrations other than the way south did when I did convert_to_south

### CODE REVIEW

**Comment by ptone** [comment]
gah - not that you were rushing to merge this one, but it is causing problems with the DB in other branches... so caveat emptor

**Comment by ptone** [comment]
The issue seems to be that the */migrations folders remained in working dir when switching branches, but I had reverted to a backup db that must have been missing some tables.  Removing the */migrations folders fixed it up.

So in short, this change will need its own mini-migration story and docs, with some repeatability testing before it is merged, and perhaps could be done as a script/patch of some sort if git is not the cleanest or reliable way to do it.

**Comment by audreyfeldroy** [comment]
Purposely holding off on this one until we're fully off of sqlite.  But it's a good thing to do.  I'm thinking the best way to test this will be with well-documented sample project fixtures.  I'd like to talk about this one in person sometime.

**Comment by ptone** [comment]
deferring

**Pull request closed without merging**
